; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Users\brandon\Documents\Systems Organization\Classwork\4-13_Array_v_Pointer\ClearArrayIndex\ClearArrayIndex\clear_array_index.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?clear_array_index@@YAXQAHH@Z			; clear_array_index
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\users\brandon\documents\systems organization\classwork\4-13_array_v_pointer\cleararrayindex\cleararrayindex\clear_array_index.cpp
rtc$TMZ	SEGMENT
;__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
;__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT ?clear_array_index@@YAXQAHH@Z
_TEXT	SEGMENT
_k$2537 = -8						; size = 4
_ary$ = 8						; size = 4
_size$ = 12						; size = 4
?clear_array_index@@YAXQAHH@Z PROC			; clear_array_index, COMDAT

; 3    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 4    : 	for (int k = 0; k < size; k++)

	mov	DWORD PTR _k$2537[ebp], 0
	mov	ecx, DWORD PTR _ary$[ebp]	; modified
	jmp	SHORT $LN3@clear_arra
$LN2@clear_arra:
	mov	eax, DWORD PTR _k$2537[ebp]
	add	eax, 1
	mov	DWORD PTR _k$2537[ebp], eax
$LN3@clear_arra:
	mov	eax, DWORD PTR _k$2537[ebp]
	cmp	eax, DWORD PTR _size$[ebp]
	jge	SHORT $LN4@clear_arra

; 5    : 		ary[k] = 0;

	mov	eax, DWORD PTR _k$2537[ebp]
	mov	DWORD PTR [ecx+eax*4], 0
	jmp	SHORT $LN2@clear_arra
$LN4@clear_arra:

; 6    : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?clear_array_index@@YAXQAHH@Z ENDP			; clear_array_index
_TEXT	ENDS
END
